backoffice/urls.py
from django.urls import path

from backoffice.views import *
from django.contrib.auth import views as auth_views

app_name = 'bo'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('departamento/add/', DepartamentoAdd.as_view(), name='departamento-add'),
    path('departamento/', DepartamentoList.as_view(), name='departamento-list'),
    path('departamento/edit/<int:pk>', DepartamentoEdit.as_view(), name='departamento-edit'),
    path('departamento/delete/<int:pk>', DepartamentoDelete.as_view(), name='departamento-delete'),
    path('departamento/detail/<int:pk>', DepartamentoDetail.as_view(), name='departamento-detail'),

    path('estacionamiento/add/', EstacionamientoAdd.as_view(), name='estacionamiento-add'),
    path('estacionamiento/', EstacionamientoList.as_view(), name='estacionamiento-list'),
    path('estacionamiento/edit/<int:pk>', EstacionamientoEdit.as_view(), name='estacionamiento-edit'),

    path('api/v1/departamento/', ApiDepartamentoList.as_view()),
    path('api/v1/provincia/', ApiProvinciaList.as_view()),
    path('api/v1/distrito/', ApiDistritoList.as_view()),
    path('api/v1/estacionamiento/', ApiEstacionamientoList.as_view()),
    path('api/v1/estacionamiento/<int:pk>', ApiEstacionamientoEdit.as_view()),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

parkApp/urls.py
from django.contrib import admin
from django.urls import path, include

from backoffice.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backoffice.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

backoffice/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Departamento(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Provincia(models.Model):
    nombre = models.CharField(max_length=50)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Distrito(models.Model):
    nombre = models.CharField(max_length=50)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Estacionamiento(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=80, null=True, blank=True)
    latitud = models.DecimalField(max_digits=9, decimal_places=7)
    longitud = models.DecimalField(max_digits=9, decimal_places=7)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, null=True, blank=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE, null=True, blank=True)
    distrito = models.ForeignKey(Distrito, on_delete=models.CASCADE, null=True, blank=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

backoffice/forms.py
from django import forms
from django.core.exceptions import ValidationError

from backoffice.models import *


class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super().clean()
        nombre = cleaned_data.get("nombre")

        if len(nombre) < 4:
            self.add_error('nombre', 'Nombre muy pequeño')

        existe = Departamento.objects.filter(nombre__contains=nombre).exclude(id=self.instance.pk)
        if existe:
            self.add_error('nombre', 'Nombre ya existe')


class EstacionamientoForm(forms.ModelForm):
    class Meta:
        model = Estacionamiento
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

backoffice/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView, FormView, \
    RedirectView
from rest_framework import generics
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.permissions import IsAuthenticated

from backoffice.forms import *
from backoffice.models import *
from backoffice.serializer import *


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = 'Inicio'
        return context


class DepartamentoList(ListView, LoginRequiredMixin):
    template_name = 'departamento/list.html'
    model = Departamento


class DepartamentoAdd(CreateView):
    template_name = 'base/add.html'
    model = Departamento
    form_class = DepartamentoForm
    success_url = reverse_lazy('bo:departamento-list')


class DepartamentoEdit(UpdateView):
    template_name = 'base/edit.html'
    model = Departamento
    form_class = DepartamentoForm
    success_url = reverse_lazy('bo:departamento-list')


class DepartamentoDelete(DeleteView):
    template_name = 'departamento/delete.html'
    model = Departamento
    success_url = reverse_lazy('bo:departamento-list')


class DepartamentoDetail(DetailView):
    template_name = 'departamento/detail.html'
    model = Departamento


class EstacionamientoList(ListView):
    template_name = 'estacionamiento/list.html'
    model = Estacionamiento


class EstacionamientoAdd(CreateView):
    template_name = 'estacionamiento/add_edit.html'
    model = Estacionamiento
    form_class = EstacionamientoForm
    success_url = reverse_lazy('bo:estacionamiento-list')


class EstacionamientoEdit(UpdateView):
    template_name = 'estacionamiento/add_edit.html'
    model = Estacionamiento
    form_class = EstacionamientoForm
    success_url = reverse_lazy('bo:estacionamiento-list')


class ApiDepartamentoList(generics.ListCreateAPIView):
    queryset = Departamento.objects.all()
    serializer_class = DepartamentoSerializer


class ApiProvinciaList(generics.ListCreateAPIView):
    serializer_class = ProvinciaSerializer

    def get_queryset(self):

        queryset = Provincia.objects.all()

        departamento = self.request.query_params.get('departamento', None)
        if departamento is not None:
            queryset = queryset.filter(departamento__nombre__contains=departamento)

        departamento_id = self.request.query_params.get('departamento_id', None)
        if departamento_id is not None:
            queryset = queryset.filter(departamento__id=departamento_id)

        return queryset


class ApiDistritoList(generics.ListCreateAPIView):
    queryset = Distrito.objects.all()
    serializer_class = DistritoSerializer


class ApiEstacionamientoList(generics.ListCreateAPIView):
    serializer_class = EstacionamientoSerializer

    def get_queryset(self):

        queryset = Estacionamiento.objects.all()

        nombre = self.request.query_params.get('nombre', None)
        if nombre is not None:
            queryset = queryset.filter(nombre__contains=nombre)

        return queryset


class ApiEstacionamientoEdit(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = EstacionamientoSerializer
    queryset = Estacionamiento.objects.all()


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = reverse_lazy("bo:index")

    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return HttpResponseRedirect(self.get_success_url())
    #     else:
    #         return super(LoginView, self).dispatch(request, *args, **kwargs)
    #
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    pattern_name = 'bo:index'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

backoffice/templates/base/add.html
{% extends 'base.html' %}

{% block main %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Agregar</h1>
    </div>
    {{ form.non_field_errors }}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock %}

backoffice/templates/base/edit.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editar</h1>
    </div>
    {{ form.non_field_errors }}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock %}

backoffice/templates/departamento-clases/list.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Listado con clases</h1>
    </div>
    <div class="form-group">
        <a class="btn btn-primary" href="{% url 'departamento-class-add' %}" role="button">Agregar</a>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for c in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ c.nombre }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'departamento-class-edit' c.id %}" role="button">Edit</a>
                        <a class="btn btn-danger" href="{% url 'departamento-class-delete' c.id %}" role="button">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

backoffice/templates/departamento/delete.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Eliminar</h1>
    </div>
    {{ object.nombre }}
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Eliminar</button>
    </form>

{% endblock %}

backoffice/templates/departamento/detail.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Agregar</h1>
    </div>
    <div class="form-group">
    {{ object.nombre }}
    </div>>

{% endblock %}

backoffice/templates/departamento/list.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Listado</h1>
    </div>
    <div class="form-group">
        <a class="btn btn-primary" href="{% url 'bo:departamento-add' %}" role="button">Agregar</a>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for c in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ c.nombre }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'bo:departamento-edit' c.id %}" role="button">Edit</a>
                        <a class="btn btn-danger" href="{% url 'bo:departamento-delete' c.id %}" role="button">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

backoffice/templates/estacionamiento/add_edit.html
{% extends 'base.html' %}

{% block main %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Agregar</h1>
    </div>
    <form method="post">

        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {

            var departamento = $('#id_departamento').val();
            var provincia = $('#id_provincia').val();
            var distrito = $('#id_distrito').val();

            $('#id_departamento').empty();
            $('#id_provincia').empty();
            $('#id_distrito').empty();

            $.ajax({
                type: 'GET',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                url: '/backoffice/api/v1/departamento',
                success: function (result) {
                    $('#id_departamento').append($('<option>', {
                        value: '',
                        text: 'Selecciona el departamento'
                    }));
                    $.each(result, function (i, item) {
                        $('#id_departamento').append($('<option>', {
                            value: item.id,
                            text: item.nombre
                        }));
                    });
                    $("#id_departamento").val(departamento);
                    $("#id_departamento").change();
                }
            });


            $('#id_departamento').change(function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    contentType: 'application/json; charset=utf-8',
                    url: '/backoffice/api/v1/provincia/?departamento_id=' + $('#id_departamento').val(),
                    success: function (result) {
                        $('#id_provincia').empty();
                        $('#id_provincia').append($('<option>', {
                            value: '',
                            text: 'Selecciona la provincia'
                        }));
                        $.each(result, function (i, item) {
                            $('#id_provincia').append($('<option>', {
                                value: item.id,
                                text: item.nombre
                            }));
                        });
                        $("#id_provincia").val(provincia);
                    }
                });

            });

        });
    </script>

{% endblock js %}

backoffice/templates/estacionamiento/list.html
{% extends 'base.html' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Listado</h1>
    </div>
    <div class="form-group">
        <a class="btn btn-primary" href="{% url 'bo:estacionamiento-add' %}" role="button">Agregar</a>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for c in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ c.nombre }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'bo:estacionamiento-edit' c.id %}" role="button">Edit</a>
{#                        <a class="btn btn-danger" href="{% url 'bo:departamento-delete' c.id %}" role="button">Delete</a>#}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

backoffice/templates/index.html
{% extends 'base.html' %}

{% block main %}

            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">{{ msg }}</h1>
            </div>
{% endblock main %}

backoffice/templates/login.html
{% load static %}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body class="white-bg">

<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <p>Escribe tu <b>dirección de correo electrónico y contraseña.</b>
        </p>

        {% if form.errors %}
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                Su nombre de usuario y/o contraseña no coinciden. Inténtalo de nuevo.
            </div>

        {% endif %}
        <form method="post" role="form">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" placeholder="correo electrónico" required="" name="username">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="contraseña" required="" name="password">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Conectarse</button>
        </form>
    </div>
</div>

<!-- Mainly scripts -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>parkApp</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock css %}

</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">{{ user }}</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{%  url 'bo:logout' %}">Sign out</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            <span data-feather="home"></span>
                            Inicio <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:estacionamiento-list' %}">
                            <span data-feather="file"></span>
                            Estacionamiento
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:departamento-list' %}">
                            <span data-feather="shopping-cart"></span>
                            Departamento
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Provincia
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Distrito
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block main %}
            {% endblock main %}
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

{% block js %}
{% endblock js %}

</body>
</html>